### ISSUE TITLE
Allow user to specify a timeout when adding data to an index

### ISSUE THREAD

**Issue by awintrip** [PlayNetwork/esimport#2]
While adding data to an index, the connection timed out.  The result was a requests.exceptions.Timeout exception:

``` Bash
clearing existing documents from localhost:9200/[index]/timezone
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/esimport/__main__.py", line 108, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/esimport/__main__.py", line 94, in main
    verify = args.skip_verify)
  File "/usr/lib/python2.7/site-packages/esimport/esimport.py", line 46, in import_data
    es.clear_documents(index_name, type_name)
  File "/usr/lib/python2.7/site-packages/esimport/elasticsearch.py", line 30, in clear_documents
    raise e
requests.exceptions.Timeout: HTTPConnectionPool(host='localhost', port=9200): Request timed out. (timeout=30)
```

Clearly, suppressing this error is undesirable.  I simply think we should allow the user to specify a timeout rather than using the default.

**Comment by brozeph** [comment]
Fixed in v0.1.7

Allowing user to specify timeout with `-T` options, but also upping default timeout from 30 to 60.
