### ISSUE TITLE
When processing field translations, not providing original column name results in a KeyError exception

### ISSUE THREAD

**Issue by awintrip** [PlayNetwork/esimport#3]
When processing field translations, not providing the original field name in an old/new pair results in a KeyError exception.

Sample input:

```
Song_id,Title,,YearPublished
trackToken,title,artistName,year
```

Sample output:

``` Python
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/esimport/__main__.py", line 108, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/esimport/__main__.py", line 94, in main
    verify = args.skip_verify)
  File "/usr/lib/python2.7/site-packages/esimport/esimport.py", line 82, in import_data
    show_status)
  File "/usr/lib/python2.7/site-packages/esimport/elasticsearch.py", line 74, in bulk_index_docs
    docs = [json.dumps(doc) for doc in bulk_index_generator(iterable)]
  File "/usr/lib/python2.7/site-packages/esimport/elasticsearch.py", line 70, in bulk_index_generator
    for d in it:
  File "/usr/lib/python2.7/site-packages/esimport/esimport.py", line 116, in field_filter
    yield dict((fieldvalues[keys.index(k)], d[k]) for k in keys if k in original_keys)
  File "/usr/lib/python2.7/site-packages/esimport/esimport.py", line 116, in <genexpr>
    yield dict((fieldvalues[keys.index(k)], d[k]) for k in keys if k in original_keys)
KeyError: ''
```

**Comment by brozeph** [comment]
Fixed in v0.1.7

If column name is not supplied, ignoring the column all together for now.
