### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by SundarPPE** [PlayNetwork/esimport#7]
Do you guys know how to fix it.?

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/esimport/__main__.py", line 110, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/esimport/**main**.py", line 96, in main
    verify = args.skip_verify)
  File "/usr/lib/python2.7/site-packages/esimport/esimport.py", line 44, in import_data
    data_lines = utils.retrieve_file_lines(filename)
  File "/usr/lib/python2.7/site-packages/esimport/utils.py", line 23, in retrieve_file_lines
    decoded_contents = retrieve_file(filename)
  File "/usr/lib/python2.7/site-packages/esimport/utils.py", line 13, in retrieve_file
    decoded_contents = original_contents.decode('utf-8-sig').encode('utf-8')
MemoryError

Thanks

**Comment by brozeph** [comment]
Hi @SundarPPE, how large is the file you are reading in?

**Comment by SundarPPE** [comment]
170MB

**Comment by SundarPPE** [comment]
I have managed to use -bc, now it is working .Thanks

**Comment by antimirov** [comment]
Guys, sorry, I just had such a good laugh this morning when also having this error:

def retrieve_file(filename):
	with open(filename, 'rb') as f:
		original_contents = f.read()

Why, why, why!!! does this tool have to read the whole file with .read()? Why not reading it line by line, it's so simple and it's possible now to read giant files without a problem.
